"""
Convert a LIBERO RLDS dataset to LeRobot format for OpenPi finetuning.

Usage:
  uv run examples/libero/convert_libero_data_to_lerobot.py \
    --data-dir ~/openpi/data/modified_libero_rlds \
    --task-filter "turn on the stove and put the moka pot on it" \
    --repo-id libero_10/stove_moka

If --task-filter is omitted, all episodes from every suite are included.
If --repo-id is omitted, it is auto-generated by slugifying the task filter string.

Prerequisites:
  uv pip install tensorflow tensorflow_datasets

Download raw data from https://huggingface.co/datasets/openvla/modified_libero_rlds
"""

import pathlib
import re
import shutil

from lerobot.common.datasets.lerobot_dataset import LeRobotDataset
import tensorflow_datasets as tfds
import tyro

RAW_DATASET_NAMES = [
    "libero_10_no_noops",
    "libero_goal_no_noops",
    "libero_object_no_noops",
    "libero_spatial_no_noops",
]


def _slugify(text: str, max_len: int = 60) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")
    return slug[:max_len].rstrip("_")


def _make_repo_id(task_filter: str | None) -> str:
    suite_tag = "_".join(n.replace("_no_noops", "") for n in RAW_DATASET_NAMES)
    if task_filter is None:
        return f"{suite_tag}/all_tasks"
    return f"{suite_tag}/{_slugify(task_filter)}"


def main(
    data_dir: str,
    *,
    task_filter: str | None = "turn on the stove and put the moka pot on it",
    repo_id: str | None = None,
    push_to_hub: bool = False,
):
    data_dir_path = pathlib.Path(data_dir).expanduser().resolve()
    repo_id = repo_id or _make_repo_id(task_filter)
    output_path = data_dir_path.parent / "lerobot" / repo_id
    if output_path.exists():
        shutil.rmtree(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    dataset = LeRobotDataset.create(
        repo_id=repo_id,
        root=output_path,
        robot_type="panda",
        fps=10,
        features={
            "image": {
                "dtype": "image",
                "shape": (256, 256, 3),
                "names": ["height", "width", "channel"],
            },
            "wrist_image": {
                "dtype": "image",
                "shape": (256, 256, 3),
                "names": ["height", "width", "channel"],
            },
            "state": {
                "dtype": "float32",
                "shape": (8,),
                "names": ["state"],
            },
            "actions": {
                "dtype": "float32",
                "shape": (7,),
                "names": ["actions"],
            },
        },
        image_writer_threads=10,
        image_writer_processes=5,
    )

    included = 0
    skipped = 0
    for raw_dataset_name in RAW_DATASET_NAMES:
        raw_dataset = tfds.load(raw_dataset_name, data_dir=data_dir, split="train")
        for episode in raw_dataset:
            step_iter = episode["steps"].as_numpy_iterator()
            if task_filter is not None:
                first = next(step_iter, None)
                if first is None:
                    continue
                if first["language_instruction"].decode() != task_filter:
                    skipped += 1
                    continue
                step_iter = episode["steps"].as_numpy_iterator()

            included += 1
            for step in step_iter:
                dataset.add_frame(
                    {
                        "image": step["observation"]["image"],
                        "wrist_image": step["observation"]["wrist_image"],
                        "state": step["observation"]["state"],
                        "actions": step["action"],
                        "task": step["language_instruction"].decode(),
                    }
                )
            dataset.save_episode()

    if push_to_hub:
        dataset.push_to_hub(
            tags=["libero", "panda", "rlds"],
            private=False,
            push_videos=True,
            license="apache-2.0",
        )

    print(f"Included {included} episodes, skipped {skipped}")
    print(f"repo_id: {repo_id}")
    print(f"LeRobot dataset written to: {output_path}")


if __name__ == "__main__":
    tyro.cli(main)
